name: 'DocuCat'
description: 'An AI assistant that generates or updates documents from changes in a GitHub pull request'
author: 'lu'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Get changed files
      id: changed-files
      shell: bash
      run: python ${{ github.action_path }}/detect_changes.py
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
